### ISSUE TITLE
error message when exporting shapefile in version 2.1

### ISSUE THREAD

**Issue by eortizb** [shawnlaffan/biodiverse#715]
I did a richness analysis (2.1 version) and when I want to export the shapefile the following message appears

Internal error in autodie/Fatal processing CORE::open: Can't locate if.pm in @INC (you may need to install the if module) (@INC contains: C:\lib C:\Biodiverse\lib C:\Users\ENRIQU~1\AppData\Local\Temp\par-456e7269717565204f7274697a\cache-94eeeea71fd4199d0b4442f147e554575159fad5\inc\lib C:\Users\ENRIQU~1\AppData\Local\Temp\par-456e7269717565204f7274697a\cache-94eeeea71fd4199d0b4442f147e554575159fad5\inc CODE(0x3087e18) CODE(0x3088010)) at (eval 564) line 6.
BEGIN failed--compilation aborted at (eval 564) line 6.
 at Biodiverse/BaseStruct.pm line 873.
 at Biodiverse/GUI/Export.pm line 128.

What do I need to solve it?
Best wishes.

Enrique Ortiz

**Comment by shawnlaffan** [comment]
Thanks for reporting.  This is a known issue (#711).  I need to release an updated version of the executable to fix it.  

I'll aim to get a new version uploaded in the next day or so, and post here when it is done.  

Until then, you could export to geotiff and then use a GIS to convert the rasters it to polygon files.

**Comment by shawnlaffan** [comment]
I have uploaded a new version that should fix the problem.  Could you please test it and let me know if it works for you?  
http://biodiverse.unsw.edu.au/downloads/biodiverse_2.1_win.zip

**Comment by eortizb** [comment]
Thanks for your quick response.
I have tried the version sent, but the error message still appears.

Internal error in autodie/Fatal processing CORE::open: Can't locate if.pm
in @INC (you may need to install the if module) (@INC contains: C:\lib
C:\Biodiverse\lib
C:\Users\ENRIQU~1\AppData\Local\Temp\par-456e7269717565204f7274697a\cache-94eeeea71fd4199d0b4442f147e554575159fad5\inc\lib
C:\Users\ENRIQU~1\AppData\Local\Temp\par-456e7269717565204f7274697a\cache-94eeeea71fd4199d0b4442f147e554575159fad5\inc
CODE(0x311f8f8) CODE(0x311faf0)) at (eval 564) line 6.
BEGIN failed--compilation aborted at (eval 564) line 6.
 at Biodiverse/BaseStruct.pm line 873.
 at Biodiverse/GUI/Export.pm line 128.

**Comment by shawnlaffan** [comment]
Hello Enrique,

Could you please double check that you have downloaded the new version and are using it? 

The folder names in your error message are identical in the original and most recent reports.  The second one is calculated using the checksum of the executable, and this will differ for the new version.  

As another check, the size of the new exe version is  34,466 kilobytes.  The previous version is 38,496.

**Comment by eortizb** [comment]
Hi!
Yes, I can export the files. I'm sorry, I confused the executable files,
but now I can export to shapefile.
Thank you!

Enrique Ortiz

**Comment by shawnlaffan** [comment]
Not a problem Enrique,

Thanks for confirming, and I will mark this issue as fixed.  

Shawn.
